from .base_repo import BaseRepo
from .cliente_repo import ClienteRepo
from .empleada_repo import EmpleadaRepo
from .servicio_repo import ServicioRepo
from .metodo_pago_repo import MetodoPagoRepo
from .turno_repo import TurnoRepo
from .caja_repo import CajaRepo
from .proveedor_repo import ProveedorRepo
from .producto_repo import ProductoRepo
from .compra_repo import CompraRepo